
# POSTGRES DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}   # simple for assignment

---

# POSTGRES SERVICE  (IMPORTANT name=db)

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---

# DJANGO DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: django
          image: app1:v01
          imagePullPolicy: Never   # use your local docker image
          ports:
            - containerPort: 8001
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres

---

# DJANGO SERVICE (expose outside)

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001

