# Generated by Django 6.0.1 on 2026-02-05 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUserInfo_View',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=255)),
                ('user_date_of_creation', models.DateField()),
                ('user_last_passcode_update', models.DateField(null=True)),
                ('user_active', models.PositiveSmallIntegerField(null=True)),
                ('user_deleted', models.PositiveSmallIntegerField(null=True)),
                ('user_role', models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')], null=True)),
                ('login_session_id', models.CharField(max_length=64, null=True)),
                ('login_date_time', models.DateTimeField(null=True)),
                ('jwt_token', models.TextField(null=True)),
                ('login_is_active', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('team_id', models.CharField(max_length=10, null=True)),
                ('team_name', models.CharField(max_length=15, null=True)),
                ('team_created_by', models.CharField(max_length=10, null=True)),
                ('team_created_datetime', models.DateTimeField(null=True)),
                ('team_deleted', models.PositiveSmallIntegerField(null=True)),
                ('team_user_team_role', models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')], null=True)),
                ('team_user_date_of_creation', models.DateTimeField(null=True)),
                ('team_user_active', models.PositiveSmallIntegerField(null=True)),
                ('team_user_deleted', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'AllUserInfo_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=15)),
                ('team_created_by', models.CharField(max_length=10)),
                ('team_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('team_deleted', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_date_of_creation', models.DateField(auto_now_add=True)),
                ('user_last_passcode_update', models.DateField(null=True)),
                ('user_active', models.PositiveSmallIntegerField(default=1)),
                ('user_deleted', models.PositiveSmallIntegerField(default=0)),
                ('user_role', models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')])),
                ('user_photo_path', models.CharField(blank=True, max_length=45, null=True)),
                ('user_photo_link', models.CharField(blank=True, max_length=45, null=True)),
                ('user_fullname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TeamUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_user_team_role', models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')])),
                ('team_user_date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('team_user_active', models.PositiveSmallIntegerField(default=1)),
                ('team_user_deleted', models.PositiveSmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app1.teaminfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='app1.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app1.userinfo'),
        ),
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_session_id', models.CharField(max_length=64, unique=True)),
                ('login_date_time', models.DateTimeField(auto_now_add=True)),
                ('jwt_token', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userinfo')),
            ],
        ),
    ]
