# Generated by Django 6.0.1 on 2026-01-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('user_date_of_creation', models.DateField()),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.IntegerField()),
                ('user_contact_no', models.CharField(max_length=10, unique=True)),
                ('user_address', models.CharField(max_length=100)),
                ('user_current_company', models.CharField(max_length=50)),
                ('user_yoe', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app1.userinfo')),
            ],
        ),
    ]
