# Generated by Django 6.0.1 on 2026-01-29 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_date_of_creation',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='12345', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
