# Generated by Django 6.0.1 on 2026-02-05 09:28

from django.db import migrations

VIEW_SQL = """
CREATE OR REPLACE VIEW AllTeamInfo_View AS

SELECT
    
    ui.user_id,
        
    ti.team_id,
    ti.team_name,
    ti.team_created_by,
    ti.team_created_datetime,
    ti.team_deleted,

    
    tu.team_user_team_role,
    tu.team_user_date_of_creation,
    tu.team_user_active,
    tu.team_user_deleted

FROM app1_userinfo ui

LEFT JOIN app1_teamusers tu
    ON tu.user_id = ui.user_id

LEFT JOIN app1_teaminfo ti
    ON ti.team_id = tu.team_id;
"""


DROP_SQL = """
DROP VIEW IF EXISTS AllTeamInfo_View;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_AllUserInfo_View'),
    ]

    operations = [
        migrations.RunSQL(
            sql=VIEW_SQL,
            reverse_sql=DROP_SQL,
        ),
    ]
