# Generated by Django 6.0.1 on 2026-02-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_AllUserInfo_View'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='team_deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app1.userinfo'),
        ),
        migrations.AlterField(
            model_name='teamusers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app1.teaminfo'),
        ),
        migrations.AlterField(
            model_name='teamusers',
            name='team_uer_team_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')]),
        ),
        migrations.AlterField(
            model_name='teamusers',
            name='team_user_active',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teamusers',
            name='team_user_deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='app1.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_active',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_lat_passcode_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_photo_link',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_photo_path',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')]),
        ),
    ]
