# Generated by Django 6.0.1 on 2026-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_AllTeamInfo_View'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTeamInfo_View',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=15, null=True)),
                ('team_created_by', models.CharField(max_length=10, null=True)),
                ('team_created_datetime', models.DateTimeField(null=True)),
                ('team_deleted', models.PositiveSmallIntegerField(null=True)),
                ('team_user_team_role', models.PositiveSmallIntegerField(choices=[(1, 'Project Owner'), (2, 'Maintainer'), (3, 'Developer')], null=True)),
                ('team_user_date_of_creation', models.DateTimeField(null=True)),
                ('team_user_active', models.PositiveSmallIntegerField(null=True)),
                ('team_user_deleted', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'allteaminfo_view',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='alluserinfo_view',
            table='alluserinfo_view',
        ),
    ]
