# Generated by Django 6.0.1 on 2026-01-29 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userlogininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogininfo',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='session_key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
