# Generated by Django 6.0.1 on 2026-02-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_teaminfo_team_deleted_alter_teaminfo_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamusers',
            old_name='team_uer_team_role',
            new_name='team_user_team_role',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_lat_passcode_update',
            new_name='user_last_passcode_update',
        ),
    ]
