# Generated by Django 6.0.1 on 2026-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userlogininfo_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
