# Generated by Django 6.0.1 on 2026-01-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
